---
    kind: pipeline
    type: exec
    name: default
    
    platform:
      os: linux
      arch: amd64
    
    steps:
    - name: build
      commands:
      - export codeBuildCommand="find ./src/  -maxdepth 1 -mindepth 1 -type d -execdir bash -c 'cd \$0 && dotnet pack --configuration Release --output /src/packages/ /p:PackageVersion=3.1.$DRONE_BUILD_NUMBER' {} \;"
      - docker run -t --rm -v /data/build_share/dotnet:/root/.dotnet -v /data/build_share/nuget:/root/.nuget -v `pwd`:/src --workdir /src mcr.microsoft.com/dotnet/core/sdk:3.1 bash -c "$codeBuildCommand"
    
    - name: build app
      commands:
      - export pushCommand="dotnet nuget push  --source http://nuget.niusys.com/v3/index.json --api-key 334EB13C-21F3-4EF0-AAB3-813836EA8194 /src/packages/"
      - docker run -t --rm -v /data/build_share/dotnet:/root/.dotnet -v /data/build_share/nuget:/root/.nuget -v `pwd`:/src --workdir /src mcr.microsoft.com/dotnet/core/sdk:3.1 bash -c "$codeBuildCommand"
